import { Level, SkillType } from '../types';

export const LEVELS: Level[] = [
    // --- TUTORIAL LEVELS (1-3) ---
    {
        id: 1,
        name: "Level 1: The Blockade",
        hint: "Goal: Save 10 Slemmings! They are headed for a cliff! Block them and turn them around.",
        spawnRate: 45,
        totalSlemmings: 15,
        toSave: 10,
        timeLimit: 240,
        terrainColor: '#2a4d15',
        spawnPos: { x: 250, y: 280 },
        exitPos: { x: 150, y: 350 },
        layoutType: 'PIT',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 0, [SkillType.BOMBER]: 5,
            [SkillType.BLOCKER]: 5, [SkillType.BUILDER]: 0, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 0, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 2,
        name: "Level 2: The Basics",
        hint: "Use FLOATERS to land safely from great heights.",
        spawnRate: 40,
        totalSlemmings: 10,
        toSave: 5,
        timeLimit: 180,
        terrainColor: '#4d2a15',
        spawnPos: { x: 100, y: 140 },
        exitPos: { x: 500, y: 340 },
        layoutType: 'PIT',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 10, [SkillType.BOMBER]: 0,
            [SkillType.BLOCKER]: 0, [SkillType.BUILDER]: 0, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 0, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 3,
        name: "Level 3: Bridging the Gap",
        hint: "Builders can create stairs. Build a bridge to reach the high ground!",
        spawnRate: 50,
        totalSlemmings: 20,
        toSave: 15,
        timeLimit: 300,
        terrainColor: '#152a4d',
        spawnPos: { x: 50, y: 340 },
        exitPos: { x: 550, y: 240 },
        layoutType: 'DIVIDE',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 5, [SkillType.BOMBER]: 5,
            [SkillType.BLOCKER]: 5, [SkillType.BUILDER]: 20, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 0, [SkillType.WALKER]: 20,
        },
    },

    // --- EASY LEVELS (4-7) ---
    {
        id: 4,
        name: "Level 4: Getting Crowded",
        spawnRate: 60,
        totalSlemmings: 30,
        toSave: 20,
        timeLimit: 300,
        terrainColor: '#4d154d',
        spawnPos: { x: 50, y: 140 },
        exitPos: { x: 550, y: 340 },
        layoutType: 'PILLARS',
        skills: {
            [SkillType.CLIMBER]: 5, [SkillType.FLOATER]: 10, [SkillType.BOMBER]: 5,
            [SkillType.BLOCKER]: 5, [SkillType.BUILDER]: 10, [SkillType.BASHER]: 5,
            [SkillType.MINER]: 5, [SkillType.DIGGER]: 5, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 5,
        name: "Level 5: Digging Down",
        spawnRate: 55,
        totalSlemmings: 25,
        toSave: 15,
        timeLimit: 300,
        terrainColor: '#4d4d15',
        spawnPos: { x: 100, y: 100 },
        exitPos: { x: 400, y: 350 },
        layoutType: 'PIT',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 5, [SkillType.BOMBER]: 0,
            [SkillType.BLOCKER]: 5, [SkillType.BUILDER]: 0, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 20, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 6,
        name: "Level 6: Up and Over",
        spawnRate: 50,
        totalSlemmings: 20,
        toSave: 18,
        timeLimit: 240,
        terrainColor: '#154d4d',
        spawnPos: { x: 50, y: 300 },
        exitPos: { x: 550, y: 300 },
        layoutType: 'STAIRS',
        skills: {
            [SkillType.CLIMBER]: 20, [SkillType.FLOATER]: 20, [SkillType.BOMBER]: 0,
            [SkillType.BLOCKER]: 0, [SkillType.BUILDER]: 0, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 0, [SkillType.WALKER]: 20,
        },
    },
    // --- MEDIUM LEVELS (7-12) ---
    {
        id: 7,
        name: "Level 7: The Gauntlet",
        spawnRate: 70,
        totalSlemmings: 40,
        toSave: 30,
        timeLimit: 360,
        terrainColor: '#4d1515',
        spawnPos: { x: 30, y: 150 },
        exitPos: { x: 600, y: 150 },
        layoutType: 'PILLARS',
        skills: {
            [SkillType.CLIMBER]: 5, [SkillType.FLOATER]: 5, [SkillType.BOMBER]: 5,
            [SkillType.BLOCKER]: 5, [SkillType.BUILDER]: 15, [SkillType.BASHER]: 5,
            [SkillType.MINER]: 5, [SkillType.DIGGER]: 5, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 8,
        name: "Level 8: Precarious",
        spawnRate: 80,
        totalSlemmings: 50,
        toSave: 45,
        timeLimit: 300,
        terrainColor: '#333333',
        spawnPos: { x: 320, y: 100 },
        exitPos: { x: 320, y: 350 },
        layoutType: 'DIVIDE',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 50, [SkillType.BOMBER]: 0,
            [SkillType.BLOCKER]: 2, [SkillType.BUILDER]: 0, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 10, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 9,
        name: "Level 9: The Long March",
        spawnRate: 90,
        totalSlemmings: 60,
        toSave: 50,
        timeLimit: 400,
        terrainColor: '#5a3d2b',
        spawnPos: { x: 20, y: 140 },
        exitPos: { x: 620, y: 340 },
        layoutType: 'STAIRS',
        skills: {
            [SkillType.CLIMBER]: 10, [SkillType.FLOATER]: 10, [SkillType.BOMBER]: 10,
            [SkillType.BLOCKER]: 10, [SkillType.BUILDER]: 20, [SkillType.BASHER]: 10,
            [SkillType.MINER]: 10, [SkillType.DIGGER]: 10, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 10,
        name: "Level 10: Just Enough",
        spawnRate: 40,
        totalSlemmings: 10,
        toSave: 10,
        timeLimit: 120,
        terrainColor: '#2b5a3d',
        spawnPos: { x: 100, y: 140 },
        exitPos: { x: 500, y: 340 },
        layoutType: 'PIT',
        skills: {
            [SkillType.CLIMBER]: 1, [SkillType.FLOATER]: 1, [SkillType.BOMBER]: 0,
            [SkillType.BLOCKER]: 1, [SkillType.BUILDER]: 2, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 1, [SkillType.WALKER]: 20,
        },
    },
    // --- HARD LEVELS (11-15) ---
    {
        id: 11,
        name: "Level 11: Speed Run",
        spawnRate: 99,
        totalSlemmings: 50,
        toSave: 10,
        timeLimit: 60,
        terrainColor: '#5a2b2b',
        spawnPos: { x: 320, y: 140 },
        exitPos: { x: 320, y: 340 },
        layoutType: 'DIVIDE',
        skills: {
            [SkillType.CLIMBER]: 5, [SkillType.FLOATER]: 50, [SkillType.BOMBER]: 5,
            [SkillType.BLOCKER]: 2, [SkillType.BUILDER]: 2, [SkillType.BASHER]: 2,
            [SkillType.MINER]: 2, [SkillType.DIGGER]: 2, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 12,
        name: "Level 12: No Return",
        spawnRate: 50,
        totalSlemmings: 30,
        toSave: 25,
        timeLimit: 240,
        terrainColor: '#3d2b5a',
        spawnPos: { x: 50, y: 140 },
        exitPos: { x: 590, y: 340 },
        layoutType: 'PILLARS',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 0, [SkillType.BOMBER]: 5,
            [SkillType.BLOCKER]: 5, [SkillType.BUILDER]: 5, [SkillType.BASHER]: 10,
            [SkillType.MINER]: 10, [SkillType.DIGGER]: 10, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 13,
        name: "Level 13: Tight Squeeze",
        spawnRate: 75,
        totalSlemmings: 40,
        toSave: 35,
        timeLimit: 300,
        terrainColor: '#2b5a5a',
        spawnPos: { x: 100, y: 200 },
        exitPos: { x: 500, y: 200 },
        layoutType: 'STAIRS',
        skills: {
            [SkillType.CLIMBER]: 5, [SkillType.FLOATER]: 0, [SkillType.BOMBER]: 5,
            [SkillType.BLOCKER]: 2, [SkillType.BUILDER]: 20, [SkillType.BASHER]: 2,
            [SkillType.MINER]: 2, [SkillType.DIGGER]: 2, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 14,
        name: "Level 14: Chaos Theory",
        spawnRate: 85,
        totalSlemmings: 60,
        toSave: 1,
        timeLimit: 120,
        terrainColor: '#5a5a2b',
        spawnPos: { x: 320, y: 50 },
        exitPos: { x: 320, y: 380 },
        layoutType: 'PIT',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 60, [SkillType.BOMBER]: 0,
            [SkillType.BLOCKER]: 0, [SkillType.BUILDER]: 0, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 0, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 15,
        name: "Level 15: The Wall",
        spawnRate: 50,
        totalSlemmings: 20,
        toSave: 15,
        timeLimit: 240,
        terrainColor: '#444444',
        spawnPos: { x: 100, y: 350 },
        exitPos: { x: 540, y: 350 },
        layoutType: 'DIVIDE',
        skills: {
            [SkillType.CLIMBER]: 10, [SkillType.FLOATER]: 0, [SkillType.BOMBER]: 2,
            [SkillType.BLOCKER]: 2, [SkillType.BUILDER]: 5, [SkillType.BASHER]: 10,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 0, [SkillType.WALKER]: 20,
        },
    },
    // --- EXPERT LEVELS (16-20) ---
    {
        id: 16,
        name: "Level 16: Leap of Faith",
        spawnRate: 60,
        totalSlemmings: 25,
        toSave: 20,
        timeLimit: 300,
        terrainColor: '#1a1a1a',
        spawnPos: { x: 50, y: 100 },
        exitPos: { x: 550, y: 300 },
        layoutType: 'PILLARS',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 25, [SkillType.BOMBER]: 0,
            [SkillType.BLOCKER]: 0, [SkillType.BUILDER]: 10, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 5, [SkillType.DIGGER]: 0, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 17,
        name: "Level 17: Demolition Crew",
        spawnRate: 40,
        totalSlemmings: 20,
        toSave: 10,
        timeLimit: 300,
        terrainColor: '#300000',
        spawnPos: { x: 320, y: 100 },
        exitPos: { x: 320, y: 350 },
        layoutType: 'STAIRS',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 0, [SkillType.BOMBER]: 10,
            [SkillType.BLOCKER]: 5, [SkillType.BUILDER]: 0, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 10, [SkillType.DIGGER]: 10, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 18,
        name: "Level 18: Ascend",
        spawnRate: 50,
        totalSlemmings: 30,
        toSave: 25,
        timeLimit: 300,
        terrainColor: '#002000',
        spawnPos: { x: 100, y: 350 },
        exitPos: { x: 500, y: 150 },
        layoutType: 'PIT',
        skills: {
            [SkillType.CLIMBER]: 10, [SkillType.FLOATER]: 0, [SkillType.BOMBER]: 0,
            [SkillType.BLOCKER]: 0, [SkillType.BUILDER]: 30, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 0, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 19,
        name: "Level 19: One Way Ticket",
        spawnRate: 30,
        totalSlemmings: 10,
        toSave: 10,
        timeLimit: 120,
        terrainColor: '#000030',
        spawnPos: { x: 50, y: 150 },
        exitPos: { x: 550, y: 150 },
        layoutType: 'DIVIDE',
        skills: {
            [SkillType.CLIMBER]: 0, [SkillType.FLOATER]: 10, [SkillType.BOMBER]: 0,
            [SkillType.BLOCKER]: 0, [SkillType.BUILDER]: 10, [SkillType.BASHER]: 0,
            [SkillType.MINER]: 0, [SkillType.DIGGER]: 0, [SkillType.WALKER]: 20,
        },
    },
    {
        id: 20,
        name: "Level 20: The Grand Escape",
        spawnRate: 99,
        totalSlemmings: 100,
        toSave: 90,
        timeLimit: 600,
        terrainColor: '#111111',
        spawnPos: { x: 320, y: 100 },
        exitPos: { x: 320, y: 350 },
        layoutType: 'PILLARS',
        skills: {
            [SkillType.CLIMBER]: 10, [SkillType.FLOATER]: 20, [SkillType.BOMBER]: 20,
            [SkillType.BLOCKER]: 10, [SkillType.BUILDER]: 30, [SkillType.BASHER]: 10,
            [SkillType.MINER]: 10, [SkillType.DIGGER]: 10, [SkillType.WALKER]: 20,
        },
    },
];
