export const SLIME_QUOTES = [
    "The goop must flow...",
    "More squishing required!",
    "Gravity is just a suggestion... for some.",
    "A perfect splatter!",
    "Do not fear the drop.",
    "Bashing is caring.",
    "Dig deep, little ones.",
    "Explosions are just spicy hugs.",
    "To build is to conquer.",
    "Block their path, save their lives.",
    "One small step for a Slemming, one giant leap for the Ooze.",
    "They bounce, they float, they... well, mostly they splat.",
    "Efficiency is key. Also, slime.",
    "The portal awaits.",
    "Guide them well, or watch them fall.",
    "Such a waste of perfectly good texture.",
    "The Slime Lord is watching.",
    "Up, up, and away!",
    "Mind the gap.",
    "Climb, my minions, climb!",
    "Preserve the biomass.",
    "Too many are perishing. Try harder.",
    "A glorious descent.",
    "Make way for the builders!",
    "Stop! Hammer time? No, BASHER time.",
    "Slemmings are renewable resources, right?",
    "Victory smells like victory... and mud.",
    "Keep them moving.",
    "Panic is not a strategy.",
    "Floaters gonna float."
];
